### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by ArbitraryRenaissance** [ArbitraryRenaissance/Favorite-Pokemon-ELO-ranking#1]
### TODO before making the release more public
- [x] Make it so that pokemon who have been chosen a fewer number of times are more likely to be selected in any given competition
- [x] Touch up the CSS of the buttons
- [x] Implement an undo button
- [x] Implement a "draw" feature
- [x] #3
- [x] Make the .html suffix vanish in the URL when navigating between pages
- [x] #2
- [ ] Add some flavor text that tells the user about the project
- [ ] Allow users to download their data and import it
- [ ] Swap out the `timestamp` element of competition entries with a `competition_number` entry.
- [ ] Write a better README.md for the repository
- [x] Implement a buffer or queue for the next pokemon, so that pokemon images for the next competition get loaded in while the user is deciding on the current competition
- [ ] Make the website mobile friendly
- [x] Implement a "rebuild" button, which rebuilds the local data to the best of its ability
- [ ] Implement a "restart" button, which allows the user to start over from scratch
- [ ] Add a favicon

### Larger tasks for future versions
- [ ] Redesign the website
- [ ] Make a page for the full leaderboard
- [ ] Make a page for the rating distribution, showing an interactive histogram of the Pokemon data
- [ ] Make an information page, with a more detailed "About" section, a link to this GitHub page, an FAQ section, attributions, etc.
- [ ] Do a top-down audit of the code, refactoring and restructuring where needed
- [ ] Give each Pokemon a public ELO rating, which aggregates the results of every user's votes
